name: Code Review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: Danger
        run: npx danger ci --text-only -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
